# Generated by Django 3.0.8 on 2020-09-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200918_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
