# Generated by Django 3.0.8 on 2020-09-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20200918_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
